import { createServerClient } from "@supabase/ssr";
import type { CookieOptions } from "@supabase/ssr";
import { type NextRequest, NextResponse } from "next/server";

import { readAdminConfiguration } from "@/lib/server/environment";

interface PendingCookie {
  name: string;
  value: string;
  options: CookieOptions;
}

/** Refreshes an existing customer session and forwards every cookie/cache
 * header generated by @supabase/ssr. Authorization stays in the data layer.
 */
export async function updateCustomerSession(request: NextRequest) {
  const { publishableKey, url } = readAdminConfiguration();
  const pendingCookies: PendingCookie[] = [];
  const pendingHeaders: Record<string, string> = {};
  const supabase = createServerClient(url, publishableKey, {
    cookies: {
      getAll() {
        return request.cookies.getAll();
      },
      setAll(cookiesToSet, headers) {
        pendingCookies.push(...cookiesToSet);
        Object.assign(pendingHeaders, headers);
      },
    },
  });

  // getClaims validates the JWT signature and triggers refresh when needed.
  // Redirects are intentionally not decided here: every protected data access
  // performs its own active-account/RLS authorization check.
  await supabase.auth.getClaims();

  for (const { name, value } of pendingCookies) {
    request.cookies.set(name, value);
  }

  const response = NextResponse.next({ request });
  for (const { name, value, options } of pendingCookies) {
    response.cookies.set(name, value, options);
  }
  for (const [name, value] of Object.entries(pendingHeaders)) {
    response.headers.set(name, value);
  }

  return response;
}
